### ISSUE TITLE
请问这个jenkins插件怎么使用

### ISSUE THREAD

**Issue by ren93** [wangkunlin/AndResGuard-Jenkins-Plugin#1]

**Comment by wangkunlin** [comment]
额，不好意思，这是我大概2年前写的了，当时是自己练手的，现在已经忘了怎么用了，如果想使用 资源压缩插件 可以参考 [AndResGuard](https://github.com/shwenzhang/AndResGuard) ，AndResGuard支持 gradle 插件方式配置，比使用 jenkins 插件的方式 简单方便。

**Comment by wangkunlin** [comment]
当时的思想就是 通过 jenkins 提供的插件入口调用 AndResGuard 的入口，并传入相应参数来工作的，所以不是很难。

**Comment by ren93** [comment]
好的，已解决
